server:
    port: 8088
#    tomcat:
#        remote-ip-header: x-forwarded-for
#        protocol-header: x-forwarded-proto
#        port-header: X-Forwarded-Port
#    use-forward-headers: true
#    compression:
#        enabled: true
#        mime-types: text/plain,application/javascript,application/x-javascript,text/css,application/xml,text/javascript,application/x-httpd-php,image/jpeg,image/gif,image/png
        
#eureka:
#    client:
#        enabled: true
#        fetch-registry: true
#        register-with-eureka: true
#        instance-info-replication-interval-seconds: 10
#        registry-fetch-interval-seconds: 10
#        instance:
#            appname: blog-service
#            instanceId: blog-service:${spring.application.instance-id:${random.value}}
#        serviceUrl:
#            defaultZone: http://106.12.36.80:10000/eureka/

spring:
    application:
        name: blog-service
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://106.12.36.80:3306/demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
        username: root
        password: 123456
        hikari:
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
    jpa:
        show-sql: true
        #hibernate:
        #    ddl-auto: create
        properties:
            hibernate:
                hbm2ddl:
                    auto: update
                    
    
jhipster:
    async:
        core-pool-size: 2
        max-pool-size: 50
        queue-capacity: 10000
    # By default CORS is disabled. Uncomment to enable.
    cors:
        allowed-origins: "*"
        allowed-methods: GET, PUT, POST, DELETE, OPTIONS
        allowed-headers: "*"
        exposed-headers:
        allow-credentials: true
        max-age: 1800
    swagger:
        default-include-pattern: /api/.*
        title: springbootDemo API documentation
        description: springbootDemo API documentation
        version: 0.0.1
        terms-of-service-url:
        contact-name:
        contact-url:
        contact-email:
        license:
        license-url:

mybatis:
    mapperLocations: classpath:mapper/*Mapper.xml
    config-location: classpath:datasource.xml

